name = "worker-ts"
main = "src/index.ts"
compatibility_date = "2022-08-14"

routes = [
    { pattern = "worker.last3lier.xyz", zone_id = "0f79268d533d0db0e1f099405969a97e" }
]

#[build.upload]
#format = "modules"
#dir = "./src"
#main = "./worker.js" # becomes "./src/worker.js"

#[[build.upload.rules]]
#type = "ESModule"
#globs = ["**/*.js"]

# Uncomment if you have a build script.
# [build]
# command = "npm run build"
